name: dartdoc
version: 0.0.1+5
author: Dart Team <misc@dartlang.org>
description: A documentation generator for Dart.
homepage: https://github.com/dart-lang/dartdoc
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  analyzer: '>=0.22.0 <0.25.0'
  args: '^0.12.2'
  cli_util: '^0.0.1'
  html: '^0.12.1'
  intl: '^0.12.0'
  logging: '^0.9.0'
  markdown: '^0.7.1'
  mustache4dart: '^1.0.9'
  path: '^1.3.0'
  quiver: '>=0.18.0 <0.22.0'
  yaml: '^2.1.0'
  pub_cache: '0.0.1+2'
  http: '^0.11.2'
  dart_style: '^0.1.7'
dev_dependencies:
  grinder: '^0.6.0'
  unittest: '^0.11.0'
  librato: '^0.0.2+1'
executables:
  dartdoc: null
